thefantasyforecasting/account/forms.py
from flask_wtf import FlaskForm, RecaptchaField
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from thefantasyforecasting.models import User


class RegistrationForm(FlaskForm):
    username = StringField('Username',
                           validators=[
                               DataRequired(message=('Please fill out this field')),
                               Length(min=3, message=('Must be 3 characters or more.')),
                               Length(max=20, message=('Must be 20 characters or less.'))
                           ])
    firstname = StringField('First Name',
                            validators=[
                                DataRequired(message=('Please fill out this field')),
                                Length(max=256, message=('Your name cannot be possible that long.'))
                            ])
    lastname = StringField('Last Name',
                            validators=[
                                DataRequired(message=('Please fill out this field')),
                                Length(max=256, message=('Your name cannot be possible that long.'))
                            ])
    email = StringField('Email',
                        validators=[
                            DataRequired(message=('Please fill out this field')),
                            Email(),
                            Length(max=120)
                        ])
    email_confirm = StringField('Confirm Email',
                                validators=[
                                    DataRequired(message=('Please fill out this field')),
                                    Length(max=120),
                                    EqualTo('email', message=('Emails must match.'))
                                ])
    password = PasswordField('Password',
                             validators=[
                                 DataRequired(message=('Please fill out this field')),
                                 Length(min=6, message=('Must contain at least 6 characters.')),
                                 Length(max=256)
                             ])
    password_confirm = PasswordField('Confirm Password',
                                     validators=[
                                         DataRequired(message=('Please fill out this field')),
                                         EqualTo('password', message=('Passwords must match.'))
                                     ])
    # recaptcha = RecaptchaField()
    submit = SubmitField('Register')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError('That username is taken. Please choose a different username.')

    def validate_email(self, email):
        email = User.query.filter_by(email=email.data).first()
        if email:
            raise ValidationError('That email already has an account.')


class LoginForm(FlaskForm):
    email = StringField('Email',
                        validators=[
                            DataRequired(),
                            Email()
                        ])
    password = PasswordField('Password',
                             validators=[
                                 DataRequired(),
                                 Length(min=6, max=20)
                             ])
    remember = BooleanField('Remember Me')
    submit = SubmitField('Login')


class RequestResetForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    submit = SubmitField('Request Password Reset')


class ResetPasswordForm(FlaskForm):
    password = PasswordField('Password', validators=[DataRequired(), Length(min=6, max=20)])
    confirm_password = PasswordField('Confirm Password',
                                     validators=[DataRequired(), Length(min=6, max=20), EqualTo('password')])
    submit = SubmitField('Reset Password')

thefantasyforecasting/account/routes.py
from flask import Blueprint, render_template, url_for, redirect, request, flash
from flask_login import login_required, current_user, login_user, logout_user
from thefantasyforecasting import bcrypt, db, global_dict
from thefantasyforecasting.models import User
from thefantasyforecasting.account.forms import RegistrationForm, LoginForm

account = Blueprint('account', __name__, template_folder='templates')


@account.route('/settings', methods=['GET', 'POST'])
@login_required
def settings():
    return render_template('settings.html', global_dict=global_dict, title='Settings')


@account.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data,
                    firstname=form.firstname.data,
                    lastname=form.lastname.data,
                    email=form.email.data,
                    password=hashed_password)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('main.home'))
    return render_template('register.html', global_dict=global_dict, title='Register', form=form, remove_header=True)


@account.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            valid_password = bcrypt.check_password_hash(user.password, form.password.data)
            if valid_password:
                login_user(user, remember=form.remember.data)
                next_page = request.args.get('next')
                if next_page:
                    return redirect(next_page)
                else:
                    return redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful.', 'danger')
    return render_template('login.html', global_dict=global_dict, title='Login', form=form)


@account.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@account.route('/achievements')
@account.route('/achievements/<string:username>')
def achievements(username):
    return render_template('achievements.html', global_dict=global_dict, title='Achievements')


@account.route('/messages')
@login_required
def messages():
    return render_template('messages.html', global_dict=global_dict, title='Messages')


@account.route('/reset_request', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    return render_template('reset_request.html', global_dict=global_dict, title='Password Reset Request')


@account.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    return render_template('reset_request.html', global_dict=global_dict, title='Password Reset')

thefantasyforecasting/account/templates/achievements.html
{% extends "layout.html" %}

{% block content %}
    <p>Paragraph text for {{ title }}</p>
{% endblock content %}

thefantasyforecasting/account/templates/login.html
{% extends "layout.html" %}

{% block styles %}
    <link
    rel="stylesheet"
    href="{{ url_for('static', filename='forms.css') }}"
    type="text/css"
    />
{% endblock %}


{% block content %}

    <div class="form-wrapper">

        <form method="POST" action="{{ url_for('account.login') }}">
            {{ form.csrf_token }}

            <fieldset class="form-field">{{ form.email.label }}{{ form.email }}
                {% if form.email.errors %}
                    <ul class="errors">
                    {% for error in form.username.errors %}
                        <li class="error">
                            <i class="fas fa-exclamation"></i> <span class="error-message">{{ error }}</span>
                        </li>
                    {% endfor %}
                    </ul>
                {% endif %}
            </fieldset>

            <fieldset class="form-field">{{ form.password.label }}{{ form.password }}
                {% if form.password.errors %}
                    <ul class="errors">
                    {% for error in form.firstname.errors %}
                        <li class="error">
                            <i class="fas fa-exclamation"></i> <span class="error-message">{{ error }}</span>
                        </li>
                    {% endfor %}
                    </ul>
                {% endif %}
            </fieldset>
            <div class="form-check">
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
            </div>
            {{ form.submit(class="btn btn-outline-info") }}
        </form>
    </div>

    <div class="">
        <small class="text-muted">
            Need An Account? <a class="" href="{{ url_for('account.register') }}">Sign Up</a>
        </small>
    </div>

    <div class="form-group">
        <small class="text-muted ml-2">
            <a href="{{ url_for('account.reset_request') }}">Forgot Password?</a>
        </small>
    </div>
{% endblock content %}

thefantasyforecasting/account/templates/messages.html
{% extends "layout.html" %}

{% block content %}
    <p>Paragraph text for {{ title }}</p>
{% endblock content %}

thefantasyforecasting/account/templates/register.html
{% extends "layout.html" %}

{% block styles %}
    <link
    rel="stylesheet"
    href="{{ url_for('static', filename='forms.css') }}"
    type="text/css"
    />
{% endblock %}


{% block content %}

<div class="form-wrapper">

    <form method="POST" action="{{ url_for('account.register') }}">
        {{ form.csrf_token }}

        <fieldset class="form-field">{{ form.username.label }}{{ form.username }}
            {% if form.username.errors %}
                <ul class="errors">
                {% for error in form.username.errors %}
                    <li class="error">
                        <i class="fas fa-exclamation"></i> <span class="error-message">{{ error }}</span>
                    </li>
                {% endfor %}
                </ul>
            {% endif %}
        </fieldset>

        <fieldset class="form-field">{{ form.firstname.label }}{{ form.firstname }}
            {% if form.firstname.errors %}
                <ul class="errors">
                {% for error in form.firstname.errors %}
                    <li class="error">
                        <i class="fas fa-exclamation"></i> <span class="error-message">{{ error }}</span>
                    </li>
                {% endfor %}
                </ul>
            {% endif %}
        </fieldset>

        <fieldset class="form-field"> {{ form.lastname.label }}{{ form.lastname }}
            {% if form.lastname.errors %}
                <ul class="errors">
                {% for error in form.lastname.errors %}
                    <li class="error">
                        <i class="fas fa-exclamation"></i> <span class="error-message">{{ error }}</span>
                    </li>
                {% endfor %}
                </ul>
            {% endif %}
        </fieldset>

        <fieldset class="form-field">{{ form.email.label }}{{ form.email }}
            {% if form.email.errors %}
                <ul class="errors">
                {% for error in form.email.errors %}
                    <li class="error">
                        <i class="fas fa-exclamation"></i> <span class="error-message">{{ error }}</span>
                    </li>
                {% endfor %}
                </ul>
            {% endif %}
        </fieldset>

        <fieldset class="form-field">{{ form.email_confirm.label }}{{ form.email_confirm }}
            {% if form.email_confirm.errors %}
                <ul class="errors">
                {% for error in form.email_confirm.errors %}
                    <li class="error">
                        <i class="fas fa-exclamation"></i> <span class="error-message">{{ error }}</span>
                    </li>
                {% endfor %}
                </ul>
            {% endif %}
        </fieldset>

        <fieldset class="form-field">{{ form.password.label }}{{ form.password }}
            {% if form.password.errors %}
                <ul class="errors">
                {% for error in form.password.errors %}
                    <li class="error">
                        <i class="fas fa-exclamation"></i> <span class="error-message">{{ error }}</span>
                    </li>
                {% endfor %}
                </ul>
            {% endif %}
        </fieldset>

        <fieldset class="form-field">{{ form.password_confirm.label }}{{ form.password_confirm }}
            {% if form.password_confirm.errors %}
                <ul class="errors">
                {% for error in form.password_confirm.errors %}
                    <li>
                        <i class="fas fa-exclamation"></i> <span class="error-message">{{ error }}</span>}
                    </li>
                {% endfor %}
                </ul>
            {% endif %}
        </fieldset>

        {{ form.recaptcha }}
        {{ form.submit }}

    </form>
</div>
{% endblock content %}

thefantasyforecasting/account/templates/reset_password.html
{% extends "layout.html" %}

{% block content %}
    <p>Paragraph text for {{ title }}</p>
{% endblock content %}

thefantasyforecasting/account/templates/reset_request.html
{% extends "layout.html" %}

{% block content %}
    <p>Paragraph text for {{ title }}</p>
{% endblock content %}

thefantasyforecasting/account/templates/settings.html
{% extends "layout.html" %}

{% block content %}
    <p>Paragraph text for {{ title }}</p>
{% endblock content %}