thefantasyforecasting/account/routes.py
from flask import Blueprint, render_template, url_for, redirect, request, flash
from flask_login import login_required, current_user, login_user, logout_user
from thefantasyforecasting import bcrypt, db, global_dict
from thefantasyforecasting.models import User
from thefantasyforecasting.account.forms import RegistrationForm, LoginForm

account = Blueprint('account', __name__, template_folder='templates')


@account.route('/settings', methods=['GET', 'POST'])
@login_required
def settings():
    return render_template('settings.html', global_dict=global_dict, title='Settings')


@account.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data,
                    firstname=form.firstname.data,
                    lastname=form.lastname.data,
                    email=form.email.data,
                    password=hashed_password)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('main.home'))
    return render_template('register.html', global_dict=global_dict, title='Register', form=form, remove_header=True)


@account.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            valid_password = bcrypt.check_password_hash(user.password, form.password.data)
            if valid_password:
                login_user(user, remember=form.remember.data)
                next_page = request.args.get('next')
                if next_page:
                    return redirect(next_page)
                else:
                    return redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful.', 'danger')
    return render_template('login.html', global_dict=global_dict, title='Login', form=form)


@account.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@account.route('/achievements')
@account.route('/achievements/<string:username>')
def achievements(username):
    return render_template('achievements.html', global_dict=global_dict, title='Achievements')


@account.route('/messages')
@login_required
def messages():
    return render_template('messages.html', global_dict=global_dict, title='Messages')


@account.route('/reset_request', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    return render_template('reset_request.html', global_dict=global_dict, title='Password Reset Request')


@account.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    return render_template('reset_request.html', global_dict=global_dict, title='Password Reset')

thefantasyforecasting/bulletin/routes.py
from flask import Blueprint, render_template, request
from thefantasyforecasting import global_dict
from thefantasyforecasting.models import Post

bulletin = Blueprint('bulletin', __name__, template_folder='templates')


@bulletin.route("/post/<int:post_id>")
def post(post_id):
    posts = Post.query.get_or_404(post_id)
    return render_template('post.html', global_dict=global_dict, post=posts)


@bulletin.route('/announcements')
def announcements():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=10)
    return render_template('announcements.html', global_dict=global_dict, title='Announcements', posts=posts)


# Need to add roll_required('Admin')
@bulletin.route('/announcements/new')
def announcements_new():
    return render_template('announcements_new.html', global_dict=global_dict, title='New Announcement')


@bulletin.route('/leaderboard')
def leaderboard():
    return render_template('leaderboard.html', global_dict=global_dict, title='Leaderboard')


@bulletin.route('/trophies')
def trophies():
    return render_template('trophies.html', global_dict=global_dict, title='Trophies')

thefantasyforecasting/extra/routes.py
from flask import Blueprint, render_template
from thefantasyforecasting import global_dict

extra = Blueprint('extra', __name__, template_folder='templates')


@extra.route('/about')
def about():
    return render_template('about.html', global_dict=global_dict, title='about')


# This should only be found in the about page
@extra.route('/contact')
def contact():
    return render_template('contact.html', global_dict=global_dict, title='contact')


@extra.route('/FAQ')
def faq():
    return render_template('FAQ.html', global_dict=global_dict, title='FAQ')


@extra.route('/privacy')
def privacy():
    return render_template('privacy.html', global_dict=global_dict, title='privacy')


@extra.route('/rules')
def rules():
    return render_template('rules.html', global_dict=global_dict, title='rules')


@extra.route('/scoring')
def scoring():
    return render_template('scoring.html', global_dict=global_dict, title='scoring')


@extra.route('/terms')
def terms():
    return render_template('terms.html', global_dict=global_dict, title='terms')

thefantasyforecasting/main/routes.py
from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import current_user, login_required
from thefantasyforecasting import global_dict
from thefantasyforecasting.utils import update_icao_list

main = Blueprint('main', __name__, template_folder='templates')


@main.route('/')
def home():
    if current_user.is_authenticated:
        return render_template('hub.html', global_dict=global_dict, title='Hub')
    return render_template('landing.html', global_dict=global_dict, title='Landing')


@main.route('/utils')
@login_required
def utils():
    cmd = request.args.get('cmd')
    if cmd is None:
        return render_template('utils.html', global_dict=global_dict, title='Utilities')

    # I want to make a button to perform the action below with model to confirm
    if cmd == 'update_icao_list':
        print('Updated ICAO List')
        #update_icao_list()
    return render_template('utils.html', global_dict=global_dict, title='Utilities')

thefantasyforecasting/templates/footer_bar.html
<footer class="container border-top navbar fixed-bottom">
    <p class="float-right">
        <a href="#">Back to top</a>
    </p>
    <p>
        © 2021 {{ global_dict.website_name }} ·
        <a href="{{ url_for('extra.privacy') }}">Privacy</a>
         ·
        <a href="{{ url_for('extra.terms') }}">Terms</a>
    </p>
</footer>

thefantasyforecasting/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>TFF - {{ title }}</title>

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    {% block styles %}{% endblock %}
</head>
<body>
    <header>
        {% if not remove_header %}
            {% include 'navigation_bar.html' %}
        {% endif %}
    </header>

    <main class="container">
        <!-- If there's a flashed message, output it at the top of the screen -->
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}

        {% block content %}  <!-- Webpage content goes here -->  {% endblock %}

    </main>

    <!-- Footer -->
    {% include 'footer_bar.html' %}
</body>

<!-- Required Bootstrap scripts for functionality -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</html>

thefantasyforecasting/templates/navigation_bar.html
<nav class="navbar navbar-expand-md fixed-top navbar-dark bg-dark">
    <div class="container"> <!-- Allows the contents to not be stuck to the sides -->
        <a href="#" class="navbar-brand">{{ global_dict.website_name }}</a>

        <!-- Button is only shown when screen is small -->
        <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarMenu">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Main navbar content -->
        <div class="collapse navbar-collapse" id="navbarMenu">
            <ul class="navbar-nav ml-auto">
                {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{{ url_for('main.home') }}" class="nav-link">My Hub</a>
                    </li>
                {% endif %}
                <li class="nav-item dropdown">
                    <a class="nav-link" href="#" role="button" data-toggle="dropdown">Challenge</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{{ url_for('challenge.forecast_new') }}">Submit</a>
                        <a class="dropdown-item" href="{{ url_for('challenge.history') }}">History</a>

                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="#" role="button" data-toggle="dropdown">Bulletin</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{{ url_for('bulletin.announcements') }}">Announcements</a>
                        <a class="dropdown-item" href="{{ url_for('bulletin.leaderboard') }}">Leaderboard</a>
                        <a class="dropdown-item" href="{{ url_for('bulletin.trophies') }}">Trophies</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="#" role="button" data-toggle="dropdown">Info</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{{ url_for('extra.rules') }}">Rules</a>
                        <a class="dropdown-item" href="{{ url_for('extra.scoring') }}">Scoring</a>
                        <a class="dropdown-item" href="{{ url_for('extra.faq') }}">FAQ</a>
                        <a class="dropdown-item" href="{{ url_for('extra.about') }}">About</a>
                    </div>
                </li>
                <!-- Only show the 'Account' option iff user is logged in -->
                {% if current_user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link" href="#" role="button" data-toggle="dropdown">Account</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{{ url_for('account.messages') }}">Messages</a>
                            <a class="dropdown-item" href="{{ url_for('account.achievements') }}">Achievements</a>
                            <a class="dropdown-item" href="{{ url_for('account.settings') }}">Settings</a>
                            <a class="dropdown-item" href="{{ url_for('account.logout') }}">Logout</a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a href="{{ url_for('account.login') }}" class="nav-link">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>