thefantasyforecasting/bulletin/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class AnnouncementForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

thefantasyforecasting/bulletin/routes.py
from flask import Blueprint, render_template, request
from thefantasyforecasting import global_dict
from thefantasyforecasting.models import Post

bulletin = Blueprint('bulletin', __name__, template_folder='templates')


@bulletin.route("/post/<int:post_id>")
def post(post_id):
    posts = Post.query.get_or_404(post_id)
    return render_template('post.html', global_dict=global_dict, post=posts)


@bulletin.route('/announcements')
def announcements():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=10)
    return render_template('announcements.html', global_dict=global_dict, title='Announcements', posts=posts)


# Need to add roll_required('Admin')
@bulletin.route('/announcements/new')
def announcements_new():
    return render_template('announcements_new.html', global_dict=global_dict, title='New Announcement')


@bulletin.route('/leaderboard')
def leaderboard():
    return render_template('leaderboard.html', global_dict=global_dict, title='Leaderboard')


@bulletin.route('/trophies')
def trophies():
    return render_template('trophies.html', global_dict=global_dict, title='Trophies')

thefantasyforecasting/bulletin/templates/announcements.html
{% extends "layout.html" %}

{% block content %}
    {% for post in posts.items %}
        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="#">{{ post.username }}</a>
                    <small class="text-muted">{{ post.date_posted.strftime('%H:%M %A, %m %b, %Y') }}</small>
                </div>
                <h2><a class="article-title" href="{{ url_for('bulletin.post', post_id=post.id_post) }}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}
    {% if posts.prev_num or posts.next_num %}
        {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=2, right_current=3) %}
            <p>{{ posts.next_num }}</p>
            <p>{{ posts.prev_num }}</p>
            <p>{{ posts.prev_num and posts.next_num }}</p>

            {% if page_num %}
                {% if posts.page == page_num %}
                    <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
                {% else %}
                    <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
                {% endif %}
            {% else %}
                ...
            {% endif %}
        {% endfor %}
    {% endif %}
{% endblock content %}

thefantasyforecasting/bulletin/templates/announcements_new.html
{% extends "layout.html" %}

{% block content %}
    <p>Paragraph text for {{ title }}</p>
{% endblock content %}

thefantasyforecasting/bulletin/templates/post.html
{% extends "layout.html" %}

{% block content %}
    <p>Paragraph text for {{ title }}</p>
{% endblock content %}

thefantasyforecasting/bulletin/templates/trophies.html
{% extends "layout.html" %}

{% block content %}
    <p>Paragraph text for {{ title }}</p>
{% endblock content %}